In [44]:
from numpy import *
a=zeros([1,2])
b_1=mat([[1,2],[1,2]])
print(shape(b)[1])
c_1=array([[1,2,3],[2,3,4]])
##[[1,2,3],[2,3,4]]本质还是列表，加上array或mat方法形成数组和矩阵
print(c)
print(shape(c)[1])
##矩阵和数组运算区别
c_2=array([[1,2,3],[1,1,1]])
c_3=array([3,2,1])
print(c_1*c_2)#数组的点乘
print(dot(c_1,c_3))#数组的矩阵乘法
b_2=mat([[1,2],[1,1]])
print(dot(b_1,b_2))
print(b_1*b_2)
##转置
b_1t=b_1.T
print(b_1t)

3
[[1 2 3]
 [2 3 4]]
3
[[1 4 9]
 [2 3 4]]
[10 16]
[[3 4]
 [3 4]]
[[3 4]
 [3 4]]
[[1 1]
 [2 2]]
