In [19]:
from numpy import *
from matplotlib.pyplot import *
def MSE(Srcimage1,Srcimage2):
    image1=imread(Srcimage1)
    image2=imread(Srcimage2)
    if image1.shape!=image2.shape:
        print('error!the size  of the two image are different.')
    sum_image=sum((image1.astype('float')-image2.astype('float'))**2)
    m=image1.shape[0]
    n=image1.shape[1]
    return sum_image/(m*n)
image1='test3-adjust1.jpg'
image2='test3_adjust2.jpg'
MSE(image1,image2)

FileNotFoundError: [Errno 2] No such file or directory: 'test3-adjust1.jpg'

In [14]:
##矩阵的运算
#a=array([[1,2],[3,4]])
#b=mat([[1,2,3],[2,3,4]])
#print(a**2)
#print(multiply(b,b))


[[ 1  4]
 [ 9 16]]
[[ 1  4  9]
 [ 4  9 16]]
