In [48]:
from numpy import *
##对数组对象
a=array([[1,2,3],[2,3,4]])
a.flatten()
a_F=a.flatten('F')
a_A=a.flatten('A')
print(a_F)
print(a_A.shape)
##对矩阵对象
A=mat([[1,2,3],[2,3,4]])
A.flatten()
A_1=A.flatten('F')
A_2=A.flatten('A')
print('===============')
print(A_1)
print(A_2)
print(shape(A_1))
print(A.shape)

[1 2 2 3 3 4]
(6,)
[[1 2 2 3 3 4]]
[[1 2 3 2 3 4]]
(1, 6)
(2, 3)


In [51]:
##三目运算
h1='a<b'
h2='a>b'
a=1
b=2
h1 if a<b else h2

'a<b'

In [69]:
a=mat([[1,2,3],[2,3,4]])
print(size(a,0))
print(size(a,1))
print(size(a))
len(a)
print(a.shape)
print(shape(a))
print('========')
b=[1,2,3]
#print(b.size)
#print(b.shape)
##对于list对象没有size和shape属性

2
3
6
(2, 3)
(2, 3)


AttributeError: 'list' object has no attribute 'size'